### ISSUE TITLE
parsing RDF+XML

### ISSUE THREAD

**Issue by biborno** [solid/solid-tutorial-rdflib.js#4] opened 2016-03-18 00:58 UTC
I am trying to read an rdf/xml file and parse it possibly in JSON or JavaScript Object or any other format. I try to search a lot of node libraries but couldn't find any good example to do so. Here is something I have tried.

```
var fs = require('fs'),
    $rdf = require('rdflib');

//var parser = new xml2js.Parser();
fs.readFile(__dirname + '/1.xml', function(err, data) {
    // Fetch data via a regular AJAX call, load from a file, or pass in a literal
    // string. In this example, it was loaded from 'https://fred.me/profile'
    var store = $rdf.graph()  // Init a new empty graph
    var contentType = 'application/rdf+xml'
    var baseUrl = ""
    var parsedGraph = $rdf.parse(data, store, baseUrl, contentType);

    $rdf.parse(data,function(triples){
        for (var i in triples){
            console.log(triples[i]);
        }
    })
});
```

here is 1.xml file

```
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:oneM2M="http://www.onem2m.org/ontology/Base_Ontology#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:cfso="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
  <oneM2M:Thing rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF">
    <cfso:hasSpecies>
      <cfso:Species rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1"/>
    </cfso:hasSpecies>
    <cfso:hasSPName>
      <cfso:SPName rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Maxfor"/>
    </cfso:hasSPName>
    <cfso:hasLocation>
      <cfso:Location rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Buyeo"/>
    </cfso:hasLocation>
    <cfso:hasCropName>
      <cfso:CropName rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato">
        <cfso:hasSpecies rdf:resource="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1"/>
      </cfso:CropName>
    </cfso:hasCropName>
    <cfso:hasControlMode>
      <cfso:ControlMode rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#A"/>
    </cfso:hasControlMode>
  </oneM2M:Thing>
</rdf:RDF>

```

The error:

```
"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" test.js
[xmldom error]  element parse error: TypeError: source.charAt is not a function 
@#[line:0,col:undefined]
d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10789
        throw new Error('Error trying to parse <' + base + '> as ' +
        ^

Error: Error trying to parse <http://IoFTriples.com/> as application/rdf+xml:
TypeError: source.substring is not a function:
TypeError: source.substring is not a function
    at appendText (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:62:20)
    at parse (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:170:4)
    at Object.XMLReader.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:30:3)
    at DOMParser.parseFromString (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\dom-parser.js:26:7)
    at Object.$rdf.Util.parseXML (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:382:31)
    at Object.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10739:30)
    at d:\WorkSpace\sparqltest\test.js:138:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
    at executeErrorCallback (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10789:15)
    at Object.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10771:5)
    at d:\WorkSpace\sparqltest\test.js:138:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Process finished with exit code 1
```

**Comment by deiu** [comment] 2016-03-18 14:51
I don't understand what the problem is. Did it fail to parse? Was there an error message? You should try to catch the error if possible (in a try/catch block):

```
try {
    $rdf.parse(data, store, uri, contentType)
    console.log(store.statements) // shows the parsed statements
} catch (err) {
    console.log(err)
}
```

`$rdf.parse()` parses data from the first function parameter and stores it in the store object you pass as the second parameter. If you want to take a look at the data, you can use the function described here: https://github.com/solid/solid-tutorial-rdflib.js#using-data-in-the-store.

Also, you should really pass the URI to `$rdf.parse()`. For example, you can use source URI `https://fred.me/profile`.

**Comment by adynata** [comment] 2016-03-18 19:25
Can you explain more the function of the source URI? What is its purpose?

I'm working on a very similar problem to the one above. The error that I keep getting is:

`Error: Error trying to parse <http://www.exampleuri.com> as application/rdf+xml:
TypeError: kb.sym is not a function`

**Comment by timbl** [comment] 2016-03-18 19:32
- The purpose of the source URL is firstly because many and often all the URLs in the RDF serialization are relative, and so need the base URI to resolved into absolute.
- In "kb.sym is not a function" it sounds you are passing something other that a graph store (aka knowledge base) as the store parameter? just guessing.  Make one with   kb = $rdf.graph()

**Comment by dmitrizagidulin** [comment] 2016-03-18 19:49
I think the line in the tutorial, `var store = $rdf.graph`, is missing parens. It should be:

`var store = $rdf.graph()`

**Comment by deiu** [comment] 2016-03-18 20:19
@dmitrizagidulin you are right! I fixed the example.

**Comment by adynata** [comment] 2016-03-18 21:20
@timbl Thank you - that's helpful to know. In my particular case, all of the base URLs are namespaced at the top of the file, so all of them can be resolved absolutely within the file, as I'm understanding it. Is there any other need to have that as an input? Adding parens to  `$rdf.graph` seems to have fixed the initial problem I was having, thanks @dmitrizagidulin!

**Comment by biborno** [comment] 2016-03-19 16:18
@deiu I have updated the source as u adviced. 
now I have added the baseURL like you said and changed the source as well like below:

```
 //---couldnot resolved yet
var fs = require('fs'),
    $rdf = require('rdflib');

//var parser = new xml2js.Parser();
fs.readFile(__dirname + '/1rdf.xml', function(err, data) {
    // Fetch data via a regular AJAX call, load from a file, or pass in a literal
    // string. In this example, it was loaded from 'https://fred.me/profile'
    var store = $rdf.graph()  // Init a new empty graph
    var contentType = 'application/rdf+xml'
    var baseUrl = "http://IoFTriples.com/"
    var parsedGraph = $rdf.parse(data, store, baseUrl, contentType);

    $rdf.parse(data,function(triples){
        for (var i in triples){
            console.log(triples[i]);
        }
    })
});
```

and the 1rdf.xml file:

```
<?xml version="1.0"?>


<!DOCTYPE rdf:RDF [
    <!ENTITY owl "http://www.w3.org/2002/07/owl#" >
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
    <!ENTITY oneM2M "http://www.onem2m.org/ontology/Base_Ontology#" >
    <!ENTITY cfso "http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#" >
]>


<rdf:RDF xmlns="http://www.IoF.com/ontology#"
     xml:base="http://www.IoF.com/ontology"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:cfso="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#"
     xmlns:oneM2M="http://www.onem2m.org/ontology/Base_Ontology#">
    <owl:Ontology rdf:about="http://www.IoF.com/ontology"/>



    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotation properties
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasControlMode -->

    <owl:AnnotationProperty rdf:about="&cfso;hasControlMode"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasCropName -->

    <owl:AnnotationProperty rdf:about="&cfso;hasCropName"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasLocation -->

    <owl:AnnotationProperty rdf:about="&cfso;hasLocation"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasSPName -->

    <owl:AnnotationProperty rdf:about="&cfso;hasSPName"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasSpecies -->

    <owl:AnnotationProperty rdf:about="&cfso;hasSpecies"/>



    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Classes
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#ControlMode -->

    <owl:Class rdf:about="&cfso;ControlMode"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CropName -->

    <owl:Class rdf:about="&cfso;CropName"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Location -->

    <owl:Class rdf:about="&cfso;Location"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#SPName -->

    <owl:Class rdf:about="&cfso;SPName"/>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Species -->

    <owl:Class rdf:about="&cfso;Species"/>



    <!-- http://www.onem2m.org/ontology/Base_Ontology#Thing -->

    <owl:Class rdf:about="&oneM2M;Thing"/>



    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Individuals
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->




    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#A -->

    <owl:NamedIndividual rdf:about="&cfso;A">
        <rdf:type rdf:resource="&cfso;ControlMode"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Buyeo -->

    <owl:NamedIndividual rdf:about="&cfso;Buyeo">
        <rdf:type rdf:resource="&cfso;Location"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato -->

    <owl:NamedIndividual rdf:about="&cfso;CharryTomato">
        <rdf:type rdf:resource="&cfso;CropName"/>
        <cfso:hasSpecies rdf:resource="&cfso;Type1"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF -->

    <owl:NamedIndividual rdf:about="&cfso;KETICF">
        <rdf:type rdf:resource="&oneM2M;Thing"/>
        <cfso:hasControlMode rdf:resource="&cfso;A"/>
        <cfso:hasLocation rdf:resource="&cfso;Buyeo"/>
        <cfso:hasCropName rdf:resource="&cfso;CharryTomato"/>
        <cfso:hasSPName rdf:resource="&cfso;Maxfor"/>
        <cfso:hasSpecies rdf:resource="&cfso;Type1"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Maxfor -->

    <owl:NamedIndividual rdf:about="&cfso;Maxfor">
        <rdf:type rdf:resource="&cfso;SPName"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1 -->

    <owl:NamedIndividual rdf:about="&cfso;Type1">
        <rdf:type rdf:resource="&cfso;Species"/>
    </owl:NamedIndividual>
</rdf:RDF>



<!-- Generated by the OWL API (version 3.4.2) http://owlapi.sourceforge.net -->
```

Now the output is gone to infinity loop. I had to press "Ctrl+C". output is something like that:

```
    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#
KETICF -->

    <owl:NamedIndividual rdf:about="&cfso;KETICF">
        <rdf:type rdf:resource="&oneM2M;Thing"/>
        <cfso:hasControlMode rdf:resource="&cfso;A"/>
        <cfso:hasLocation rdf:resource="&cfso;Buyeo"/>
        <cfso:hasCropName rdf:resource="&cfso;CharryTomato"/>
        <cfso:hasSPName rdf:resource="&cfso;Maxfor"/>
        <cfso:hasSpecies rdf:resource="&cfso;Type1"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#
Maxfor -->

    <owl:NamedIndividual rdf:about="&cfso;Maxfor">
        <rdf:type rdf:resource="&cfso;SPName"/>
    </owl:NamedIndividual>



    <!-- http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#
Type1 -->

    <owl:NamedIndividual rdf:about="&cfso;Type1">
        <rdf:type rdf:resource="&cfso;Species"/>
    </owl:NamedIndividual>
</rdf:RDF>



<!-- Generated by the OWL API (version 3.4.2) http://owlapi.sourceforge.net -->

 has no method 'indexOf'
@#[line:0,col:undefined]
```

output: 

```

"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" test.js
[xmldom error]  element parse error: TypeError: source.charAt is not a function 
@#[line:0,col:undefined]
d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10789
        throw new Error('Error trying to parse <' + base + '> as ' +
        ^

Error: Error trying to parse <http://IoFTriples.com/> as application/rdf+xml:
TypeError: source.substring is not a function:
TypeError: source.substring is not a function
    at appendText (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:62:20)
    at parse (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:170:4)
    at Object.XMLReader.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\sax.js:30:3)
    at DOMParser.parseFromString (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\xmldom\dom-parser.js:26:7)
    at Object.$rdf.Util.parseXML (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:382:31)
    at Object.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10739:30)
    at d:\WorkSpace\sparqltest\test.js:138:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
    at executeErrorCallback (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10789:15)
    at Object.parse (d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10771:5)
    at d:\WorkSpace\sparqltest\test.js:138:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Process finished with exit code 1

```

**Comment by deiu** [comment] 2016-03-21 09:45
It sounds like an error coming from xmldom. Maybe this helps: https://github.com/jindw/xmldom/issues/153

**Comment by biborno** [comment] 2016-03-22 01:11
@deiu Thank You. Solved the problem. fs.readFile returns object instead of string. here is the working source:

```
var fs = require('fs'),
    $rdf = require('rdflib');

var rdfData=fs.readFileSync(__dirname+'/1.xml').toString();

var store=$rdf.graph();
var contentType='application/rdf+xml';
var baseUrl="http://IoFTriples.com";
try{
    $rdf.parse(rdfData,store,baseUrl,contentType);

    var stms = store.statementsMatching(undefined, undefined , undefined);
    for (var i=0; i<stms.length;i++) {
        var stm = stms[i]
        console.log(stm) // the WebID of a friend

    }
} catch(err){
    console.log(err);
}
```

output:

```
D:\WorkSpace\sparqltest>node test.js
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object: NamedNode { uri: 'http://www.onem2m.org/ontology/Base_Ontology#Thing' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasSpecies' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Species' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasSPName' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Maxfor' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Maxfor' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#SPName' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasLocation' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Buyeo' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Buyeo' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Location' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasCropName' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CropName' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasSpecies' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF' },
  predicate:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#hasControlMode' },

  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#A' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
Statement {
  subject:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#A' },
  predicate: NamedNode { uri: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode {
     uri: 'http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#ControlMode' },
  why: NamedNode { uri: 'http://IoFTriples.com' } }
```

**Closed as completed** 2016-03-22 01:11 UTC
